version: '3.1'
services:
  my-service: 
    build:
      context: .
    image: openiap/angularjs:edge
    ports:
      - "80:80"
    environment: 
      - NODE_ENV=production
      - port=80
      - frontend_domain=localhost.openiap.io

      - saml_federation_metadata=https://app.openiap.io/issue/FederationMetadata/2007-06/FederationMetadata.xml
      - saml_issuer=uri:app.openiap.io/
      - api_ws_url=wss://app.openiap.io/